require('dotenv').config();
const express = require("express");
const bodyParser = require("body-parser");
const nodemailer = require("nodemailer");
var mysql = require("mysql");

const sqlemails = 'SELECT mail FROM usersinfo';
const countRows = 'SELECT COUNT(*) as total FROM usersinfo';
var rowNumber;
var mail_list = [];

const app = express();

app.use(express.static("public"));  //To use local assets
app.use(bodyParser.urlencoded({extended: true}));

app.get("/",function(req,res){
    res.sendFile(__dirname + "/infopost.html");
});

app.listen(3000, function(){
    console.log("Server started....");
});

// MySQL setup
var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    pass: '',
    database: 'formmysqlwithnodejs'
});

connection.connect(function(err){
    if(err) throw err;
    console.log('Database is connect successfully...');
});

connection.query(countRows,function(err,data){
    if(err){
        console.log('Catched errors '+err);
    }
    else{
        rowNumber = data[0].total;
        console.log('You have '+rowNumber+' rows in table');
    }
});



app.post("/",function(req,res){
    var firstName = req.body.firstName;
    var lastName = req.body.lastName;
    var username = req.body.username;
    var email = req.body.email;
    var phone = req.body.phone;
    var gender = req.body.gender;

    console.log(firstName,lastName,username,email,phone,gender);


    var sql = "insert into usersinfo values('"+firstName+"', '"+lastName+"', '"+username+"','"+email+"', '"+phone+"', '"+gender+"')"
    connection.query(sql, function (err) {
        if (err){
            res.sendFile(__dirname+"/fail.html");
            console.log(err);
            return;
        }
        else{
            res.sendFile(__dirname+"/success.html");
        }
      });

      connection.query(sqlemails, function(err, email, fields){
        for(k in email){
            mail_list.push(email[k].mail);
        }
        console.log("You have "+ mail_list.length+" mails in the database");
        if(mail_list.length == 1){
            console.log("You have enough mail to send email");
            sendMailFinal();
        }
        else{
            console.log("You don't have enough mail to send email");
        }
      });

    //connection.end();

});

app.post("/failure", function(req,res){
    res.redirect("/");
});


var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth:{
        user: process.env.EMAIL,
        pass: process.env.PASSWORD
    }
});

var mailOptions = {
    from: 'Mirror <donationdistributation@gmail.com>',
    to: mail_list,
    subject: 'No-Reply',
    text: 'This is an autogenerated mail from my newly build web-application. Do not reply the mail.'

};

sendMailFinal = function(){
    transporter.sendMail(mailOptions,function(err,data){
        if(err){
            console.log("Send Faild. reason: "+err);
        }
        else{
            console.log("Mail send successfully");
        }
    });
}

